config/routes.rb
Rails.application.routes.draw do
  get '/user/:id', to: 'users#profile', as: :user
  devise_for :users
  resources :users
  root "events#index"
  resources :events do
    member do
      get "event_attendances"
      get "cancel_event_attendances"
      end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  validates :date_time, :title, presence: true
  validates :description, presence: true
  validates :description, length: { minimum: 5}
  validates :title, length: { minimum: 5}
  belongs_to :creator, class_name: "User", foreign_key: "creator_id"
  has_many :event_attendances, foreign_key: "attended_event_id"
  has_many :attendees, through: :event_attendances, class_name: "User"
  scope :past, -> { where('date_time < ?', Date.today).order(date_time: :desc) }
  scope :future, -> { where('date_time > ?', Date.today).order(:date_time) }
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, :encrypted_password, presence: true
  has_many :event_attendances, foreign_key: 'attendee_id'
  has_many :attended_events, through: :event_attendances
   has_many :created_events, class_name: 'Event', foreign_key: 'creator_id'
end
  

app/controllers/application_controller.rb
require "application_responder"

require "application_responder"
class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :encrypted_password ])
  end
end

app/controllers/event_attendances_controller.rb
class EventAttendancesController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @events = Event.includes(:creator).all
  end

  def new
    @event = Event.new
  end
  def edit
    @event = Event.find(params[:id])
  end
  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: "Your event was updated"
    else
      render :edit
    end
  end
  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end
  def show
    @event = Event.find(params[:id])
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      flash[:success] = "Event successfully created"
      redirect_to events_path
    else
      flash.now[:error] = @event.errors.full_messages
      redirect_to new_event_path
    end
  end


  def event_attendances
    @event = Event.find(params[:id])
    unless @event.attendees.include?(current_user)
      @event.attendees << current_user
      if @event.save
        flash[:success] = 'Post successfully created'
        redirect_to @event, notice: "You have successfully joined the event."
      else
        redirect_to @event, alert: "Something went wrong. Try again."
      end
    else
      redirect_to @event, notice: "You are already on the list."
    end
  end

  def cancel_event_attendances
    @event = Event.find(params[:id])
    @event.attendees.delete(current_user)
    redirect_to @event, notice: "You are no longer attending this event"
  end

  private


    def event_params
      params.require(:event).permit(:title, :description,:date_time)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
      @events = current_user.created_events
  end
  def profile
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendances_helper.rb
module EventAttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/create.html.erb
<div class="navbar">
  <% if user_signed_in? %>
    <%= link_to "Main Page", events_path %>
    <%= link_to "Profile", user_path(current_user) %>
    <%= button_to 'Sign Out', destroy_user_session_path, method: :delete %>
  <% else %>
    <%= button_to 'Sign In', new_user_session_path %>
  <% end %>
</div>
<br>
<%= form_with(url: attend_event_path(@event), method: :post, local: true) do %>
  <% if @event.attendees.include?(current_user) %>
    <p>You are already attending this event.</p>
    <%= button_to 'Cancel Attendance', unattend_event_path(@event), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= submit_tag 'Attend Event', class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/events/edit.html.erb
<div class="navbar">
  <% if user_signed_in? %>
    <%= link_to "Main Page", events_path %>
    <%= link_to "Profile", user_path(current_user) %>
    <%= button_to 'Sign Out', destroy_user_session_path, method: :delete %>
  <% else %>
    <%= button_to 'Sign In', new_user_session_path %>
  <% end %>
</div>
<br>

<%= form_with model: @event  do |f| %>
  <% if @event.errors.any? %>
    <ul>
      <% @event.errors.full_messages.each do |error| %>
        <li> <%= error %> </li>
      <% end %>
    </ul>
  <% end %>
  <div class="form-group">
     <%= f.label :title%> <br>
    <%= f.text_field :title%> <br>
  </div>
  <div class="form-group">
      <%= f.label :description%> <br>
    <%= f.text_area :description%><br>
  </div>
  <div class="form-group">
     <%= f.label :date%> <br>
    <%= f.datetime_field :date_time%>
  </div>
  <%= f.submit%>
<% end %>

app/views/events/index.html.erb
<div class="navbar">
  <% if user_signed_in? %>
    <%= link_to "Profile", user_path(current_user) %>
    <%= link_to "New Event", new_event_path %>
    <%= button_to 'Sign Out', destroy_user_session_path, method: :delete %>
  <% else %>
    <%= button_to 'Sign In', new_user_session_path %>
  <% end %>
</div>
    <h1>Upcoming Events</h1>
<div class="upcoming">
  <% Event.future.each do |event| %>
   <h4> <%= event.title.titleize %></h4>
    <p> <%= event.date_time.strftime("%B %-d, %Y") %></p>
      <%= event.description.truncate(100) %></p>
          <%= link_to 'Learn More', event_path(event)%><br>
    <% if current_user == event.creator %>
      <%= link_to 'Edit', edit_event_path(event)%><br>
      <%= link_to 'Delete', event_path(event), method: :delete,
                            data: { confirm: "Delete this event?"} %>
     <% end %>
  <% end %>
</div>
  <% Event.past.each do |event| %>
  <div class="past">
          <h5><%= event.title.titleize %></h5>
          <p><%= event.date_time%></p>
          <p><%= event.description %></p>
          <%= link_to 'Learn More', event_path(event)%>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<div class="navbar">
  <% if user_signed_in? %>
    <%= link_to "Main Page", events_path %>
    <%= link_to "Profile", user_path(current_user) %>
    <%= button_to 'Sign Out', destroy_user_session_path, method: :delete %>
  <% else %>
    <%= button_to 'Sign In', new_user_session_path %>
  <% end %>
</div>
<br>
<%= form_with model: @event  do |f| %>
  <% if @event.errors.any? %>
    <ul>
      <% @event.errors.full_messages.each do |error| %>
        <li> <%= error %> </li>
      <% end %>
    </ul>
  <% end %>
  <div class="form-group">
     <%= f.label :title, placeholder: "Event title"%> <br>
    <%= f.text_field :title, placeholder: "Event title"%> <br>
  </div>
  <div class="form-group">
      <%= f.label :description, placeholder: "Event description"%> <br>
    <%= f.text_area :description, placeholder: "Event description"%><br>
  </div>
  <div class="form-group">
     <%= f.label :date%> <br>
    <%= f.datetime_field :date_time%>
  </div>
  <%= f.submit%>
<% end %>

app/views/events/show.html.erb
<div class="navbar">
  <% if user_signed_in? %>
    <%= link_to "Main Page", events_path %>
    <%= link_to "Profile", user_path(current_user) %>
    <%= link_to "New Event", new_event_path %>
    <%= button_to 'Sign Out', destroy_user_session_path, method: :delete %>
  <% else %>
    <%= button_to 'Sign In', new_user_session_path %>
  <% end %>
</div>
<br>

<div class="the_event">
<h1><%= @event.title.titleize %></h1>
<br>
<p><%= @event.description %><p>
<h2><%= @event.date_time %></h2>

<% if @event.creator_id == (current_user.id) %>
    <h1>Your Event</h1>
<% elsif @event.attendees.include?(current_user) %>
  <%= link_to 'Cancel Attendance', cancel_event_attendances_event_path, class: 'btn btn-outline-secondary' %>
<% else %>
  <%= link_to 'I\'m in', event_attendances_event_path, class: 'btn btn-primary' %>
<% end %>
</div>
<p>ATTENDEES</p>

<!-- Display attendees list -->
<% if @event.attendees.empty? %>
  <div class="list-group-attendees">
    <li class="list-group-item text-muted">This event has no attendees yet</li>
  </div>
<% else %>
  <div class="list-group">
    <% @event.attendees.each do |attendee| %>
      <li class="list-group-item"><%= attendee.email %></li>
    <% end %>
  </div>
<% end %>

app/views/events/view.html.erb
<div class="navbar">
  <% if user_signed_in? %>
    <%= link_to "Main Page", events_path %>
    <%= link_to "Profile", user_path(current_user) %>
    <%= button_to 'Sign Out', destroy_user_session_path, method: :delete %>
  <% else %>
    <%= button_to 'Sign In', new_user_session_path %>
  <% end %>
</div>
<br>

<h1>Events</h1>
  <div>
  <% @euser_events.each do |event| %>
  <div class="events">
  <h2><%= event.title %></h2>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Private Events" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

 <body>
    <%= yield %>
    <% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>
  </body>
</html>

app/views/users/profile.html.erb
<div class="navbar">
  <% if user_signed_in? %>
    <%= link_to "Main Page", events_path %>
    <%= button_to 'Sign Out', destroy_user_session_path, method: :delete %>
  <% else %>
    <%= button_to 'Sign In', new_user_session_path %>
  <% end %>
</div>
<br>

<div>
  <p><%= pluralize(current_user.created_events.count, 'event').upcase %> CREATED</p>
  <div>
    <% if current_user.created_events.any? %>
      <% current_user.created_events.each do |event| %>
        <%= link_to event.title, event_path(event) %>
      <% end %>
    <% else %>
      <p>No events created yet.</p>
    <% end %>
  </div>

  <p><%= pluralize(current_user.attended_events.count, 'event').upcase %> ATTENDED</p>
  <div>
    <% current_user.attended_events.each do |event| %>
      <%= link_to event.title, event_path(event) %>
    <% end %>
  </div>
</div>